plugins {
    id 'com.android.application'
}

android {
    namespace 'eu.fiskaltrust.middleware.demo.java'
    compileSdk 36

    defaultConfig {
        applicationId "eu.fiskaltrust.middleware.demo.java"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        disable 'GoogleAppIndexingWarning', 'HardcodedText', 'InvalidPackage'
        textReport true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.code.gson:gson:2.11.0'
}
